name: Pull Request

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: make build

      - name: Install stream-commp
        run: go install github.com/filecoin-project/go-fil-commp-hashhash/cmd/stream-commp@fe93a7f

      - name: Install Ruby
        run: sudo apt-get update && sudo apt install ruby && sudo gem install bundler -v 2.1.2

      - name: Install Ruby RSpec
        run: bundle install --path .bundle

      - name: Run regression test
        run: make test

