name: Release

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: make build

      - name: Tar
        run: tar -cvzf generate-car-linux-amd64.tar.gz generate-car

      - name: Upload release binaries
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: generate-car-linux-amd64.tar.gz

  release-macos-11:
    name: release macos/11
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: make build

      - name: Tar
        run: gtar -cvzf generate-car-darwin-amd64.tar.gz generate-car

      - name: Upload release binaries
        uses: SierraSoftworks/gh-releases@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: 'true'
          files: generate-car-darwin-amd64.tar.gz
